### PR TITLE
Added mocking for FindAsync and ability to add and update items in th…

### PR DESCRIPTION
**Pull request by remcobosman**
I added some mocking for FindAsync, you can specify how to find items to control what is returned when any call is made to FindAsync. Also made changed some DbQueries to DbSets and added the ability to add and update items to the internal collection.

### CODE REVIEW

**Comment by MichalJankowskii** [comment]
Great. Thank you for your help. Can you please remove changes related to ncrunch.

**Comment by remcobosman** [comment]
I will do that, also the gitignore?
________________________________

**Comment by MichalJankowskii** [comment]
Yes, Please.

**Comment by remcobosman** [comment]
Well I think I removed all traces. Let me know if you still see traces anywhere. I also think there is a bit too much duplication in setting up the mock, but I haven't found a solution for that.

**Comment by MichalJankowskii** [comment]
Hi,

I merged it to separate branch to play with a bit before making it public. And I have a few remarks:
1. you changed IEnumerable to ICollection - this change can break people that are using the library a lot of unit tests
2. FindAsync is working partially:
a. it does not work with obsolete methods
b. there is missing Find support
3. Then also Mock dbSetMock has been changed into Mock<DbSet<TEntity>> this can have the same issue as in the first point

I like your idea but we need to support that in the way that will not break anything to other people. Right now I am thinking into going to a direction that it will be added as support and injected to Return* method.

**Comment by remcobosman** [comment]
Hi,

Yes, I can understand your reasoning. I just added it because it fitted my scenario. I may spend some time on this as well, although work has been kind of busy lately.

Regards,

Remco Bosman

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Pull request merged**
